### ISSUE TITLE
This is not working out of the box.

### ISSUE THREAD

**Issue by JMIdeaMaker** [Kylmakalle/heroku-telegram-bot#4]
Here is my stackoverflow question : https://stackoverflow.com/questions/50537748/simple-telegram-bot-not-working-at-heroku-state-changed-from-up-to-crashed-pro

**Comment by Kylmakalle** [comment]
It's just a template, it shouldn't, edit files with your code.
https://github.com/Kylmakalle/heroku-telegram-bot#edit-files
