### ISSUE TITLE
Did not found below steps in GUI

### ISSUE THREAD

**Issue by jp1691** [Kylmakalle/heroku-telegram-bot#5]
Press on a small pen button, move slider and then click Confirm, that will start bot dyno.
Simply move slider back if you need to stop bot dyno, remember to click Confirm.
If for some reason it’s not working, check the logs here

How to start dyno from GUI ?

**Comment by Kylmakalle** [comment]
![image](https://user-images.githubusercontent.com/24507532/42716990-eeddf52a-8706-11e8-9232-9f0015979724.png)
