### ISSUE TITLE
question on deployment 

### ISSUE THREAD

**Issue by Liyubov** [Kylmakalle/heroku-telegram-bot#8]
thank you for the bot installation and all the setup. 
it is really clear and great.

i had question though, maybe others also had it. 

when i am deploying it (through Heroku Dashboard or without) when it tries to clone your repo there are some errors. did you also had them?

> 
>          Running command git clone -q https://github.com/Kylmakalle/pyTelegramBotAPI.git /tmp/pip-req-build-h02rpt0r
> 
>          Running command git checkout -b feature-BotAPIV3 --track origin/feature-BotAPIV3
> 
>          Switched to a new branch 'feature-BotAPIV3'
> 
>          Branch 'feature-BotAPIV3' set up to track remote branch 'feature-BotAPIV3' from 'origin'.
> 
>        Collecting https://site.org/files/package.zip (from -r /tmp/build_0790f21bca1810dd02b5d00b825b4595/requirements.txt (line 11))
> 
>          WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc1cb8b55f8>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /files/package.zip

Thanks!

**Comment by Kos03134** [comment]
First bot practice for a long time) Gonna get to your issue a bit later

**Comment by Kylmakalle** [comment]
> Edit requirements.txt with your code's dependencies

That implies you will remove fake dependencies
